Create Form
eyesofdaveed/smavyPlatform pull request #15
Opened 2023-10-25 18:14 UTC by Dimas00319

2023-10-26 03:20 UTC, Bashkanitto commented on client/src/atoms/Input.jsx
> +  width: 80%;
оставь 100%

этот переиспользуемый компонент
в других случаях может не правильно отобразится

лучше поменяй width of wrapper для данного input - та 

тоесть для flexbox дай fix ширину и padding

2023-10-26 03:21 UTC, Bashkanitto commented on client/src/atoms/Input.jsx
> +  debugger;
debugger нужен только для local development лучше их убрать

2023-10-26 03:48 UTC, Bashkanitto requested changes
в следующий раз закрепи скриншот своей работы( что бы я мог видеть результат)

измени эти моменты можеш делать merge

2023-10-26 03:48 UTC, Bashkanitto commented on client/src/organism/Form.jsx
> +  ];
ну вобще проверку делает backend и отправляет нам ошибку
нам нужн будет просто результат вывести
так что рендерить и проверять с помощью database не стоит

2023-10-26 03:48 UTC, Bashkanitto commented on client/src/organism/Form.jsx
> +    const userData = database.find((user) => user.username === uname.value);
ну тут так же

2023-10-26 03:48 UTC, Bashkanitto commented on client/src/organism/Form.jsx
> +    database[0].username += uname.value;
так же

2023-10-26 03:48 UTC, Bashkanitto commented on client/src/organism/Form.jsx
> +            <Input placeholder="Ваше имя" onChange={onChange} value={database[0].username} type="text" name="uname" required />
on change так же проверять не надо

2023-10-27 10:36 UTC, Bashkanitto approved these changes

2023-10-27 11:16 UTC, eyesofdaveed approved these changes

2023-10-27 11:17 UTC, merged