added assignments model
eyesofdaveed/smavyPlatform pull request #16
Opened 2023-10-26 05:28 UTC by DonJuvn

Created new model "Assignments.js", wrote routes for Get all, update, add assignment.

2023-10-27 06:55 UTC, darkhanzhursin commented on package-lock.json
package-lick.json server-дің (папка) ішінде тұруы керек

2023-10-27 06:57 UTC, darkhanzhursin requested changes

2023-10-27 06:57 UTC, darkhanzhursin commented on package.json
package.json server-дің (папка) ішінде тұруы керек

2023-10-28 05:32 UTC, eyesofdaveed commented on server/routes/assignments.js
> +        const newAssignment = new Assignments({
const { title, description, completed } = req.body;

2023-10-28 05:36 UTC, eyesofdaveed commented on server/routes/assignments.js
> +        const deletedAssignment = await Assignments.deleteOne({deletionCriteria
{ _id: req.params.id}

2023-10-28 06:14 UTC, merged