added findOne, deleteOne, UpdateById, deleteAll
eyesofdaveed/smavyPlatform pull request #29
Opened 2023-11-01 04:08 UTC by DonJuvn

2023-11-01 12:40 UTC, darkhanzhursin requested changes
fixes are required

2023-11-01 12:40 UTC, darkhanzhursin commented on server/api/index.js
> +        const deletionCriteria = { _id: 123 };
_id: 123
why 123?

2023-11-01 12:40 UTC, darkhanzhursin commented on server/api/index.js
> +            let entity = await this.entityModel.findByPk(id);
what and where is the findByPk() method?

2023-11-01 12:40 UTC, darkhanzhursin commented on server/api/index.js
> +            const data = await this.entityModel.destroy({where: {}, truncate: true});
what method is destroy? which library are u using?

2023-11-02 03:00 UTC, DonJuvn commented on server/api/index.js
> +            let entity = await this.entityModel.findByPk(id);
this is similar to findById method, PK is primary key

2023-11-03 08:22 UTC, darkhanzhursin approved these changes

2023-11-03 12:14 UTC, eyesofdaveed commented on server/api/index.js
> +                return res.status(200).json({ entity })
`json({data: entity})`

2023-11-03 12:14 UTC, eyesofdaveed commented on server/api/index.js
> +                return res.status(400).json({ success: false, error: `No such ${entity} present`, data: [] });
remove `success`

2023-11-03 12:15 UTC, eyesofdaveed commented on server/api/index.js
> +                return res.status(400).json({ success: false, error: `No such ${entity} present`, data: [] });
data: [],
message: ''

2023-11-03 13:06 UTC, eyesofdaveed commented on server/api/index.js
> +            let entity = await this.entityModel.findById(id).exec();
don't use `let` unless you sure that you will modify it

2023-11-07 12:56 UTC, eyesofdaveed commented on server/routes/users.js
> +router.delete('/', async (req, res) => {
you would receive `id` from `req.query`, to delete specific entity by it's `_id`

2023-11-07 12:57 UTC, eyesofdaveed approved these changes

2023-11-07 12:58 UTC, eyesofdaveed commented on server/api/index.js
> +      let id = req.params.id;
const, unless you sure that you will change the value

2023-11-07 12:58 UTC, eyesofdaveed commented on server/api/index.js
> +      const data = await this.entityModel.findById(id).exec();
blank line

2023-11-07 13:02 UTC, eyesofdaveed commented on server/api/index.js
> +      if (data) return res.status(200).json({ data: data });
`if (!data) return res.status(400).json({
          message: 'No Data Found',
          data: [],
        });`

2023-11-07 13:02 UTC, eyesofdaveed commented on server/api/index.js
> +      if (data) return res.status(200).json({ data: data });
`return res.status(200).json({ data: data });`

2023-11-07 13:04 UTC, eyesofdaveed commented on server/api/index.js
> +  async update(req, res) {
Explicitly define what should be updated, .e.g: 
`const { fieldsToUpdate} = req.body;`

2023-11-09 03:53 UTC, closed without merging